### ISSUE TITLE
Is this the final library, which will be on the IAB repo?

### ISSUE THREAD

**Issue by ydennisy** [didomi/consent-string#1]
Hello!
Thanks for this lib!
Is this the final functionality which will be provided?
And are you moving this over to the IAB tech lab [repo](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS)

**Comment by jawadst** [comment]
Hi @ydennisy 
Yes, it's the same code that is being pushed to the IAB repo: https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS/pull/1
